clickhouse_channels_column_names = {
    "id": "id",
    "username": "username",
    "userid": "userid",
    "avatar_thumbnail": "avatar_thumbnail",
    "is_official": "is_official",
    "name": "name",
    "bio_links": "bio_links",
    "total_video_visit": "total_video_visit",
    "video_count": "video_count",
    "start_date": "start_date",
    "start_date_timestamp": "start_date_timestamp",
    "followers_count": "followers_count",
    "following_count": "following_count",
    "country": "country",
    "platform": "platform",
    "is_deleted": "is_deleted",
    "created_at": "created_at",
    "updated_at": "updated_at",
    "update_count": "update_count",
    "offset": "offset",
},

clickhouse_videos_column_names = {
    "id": "id",
    "owner_username": "owner_username",
    "owner_id": "owner_id",
    "title": "title",
    "tags": "tags",
    "uid": "uid",
    "visit_count": "visit_count",
    "owner_name": "owner_name",
    "poster": "poster",
    "owner_avatar": "owner_avatar",
    "duration": "duration",
    "posted_date": "posted_date",
    "posted_timestamp": "posted_timestamp",
    "sdate_rss": "sdate_rss",
    "sdate_rss_tp": "sdate_rss_tp",
    "comments": "comments",
    "frame": "frame",
    "like_count": "like_count",
    "description": "description",
    "is_deleted": "is_deleted",
    "created_at": "created_at",
    "expire_at": "expire_at",
    "is_produce_to_kafka": "is_produce_to_kafka",
    "update_count": "update_count",
    "_ingestion_ts": "_ingestion_ts",
    "_source": "_source",
    "_raw_object": "_raw_object",
    "offset": "offset",
},

telegram_alerting_info = {
"dag_alerting_telegram_bot_token": "7513376273:AAGsUYkNj_G-EnkE9fyMdfQB-cz7o_TpN-0",
"dag_alerting_chat_id": "645115745",
"telegram_proxy": "",
}